### ISSUE TITLE
Does the outputClean LDA model generalize to other species?

### ISSUE THREAD

**Issue by davidfstein** [beliveau-lab/OligoMiner#11]
Hi,

Do you anticipate that the trained LDA model in outputClean will work well for non-human species? I am testing it on some mouse probes and receiving strange results. Particularly, for probes that bowtie2 marks as having several alignments, outputClean passes 100 percent of the candidates when I would expect fewer to pass. This is regardless of how I set the p flag (even -p 1 which seems strange). Maybe there are some caveats I need to be aware of when using the model with outputClean. I'm attaching my input fasta file in case that sheds some light.

Thanks!
[mouse.txt](https://github.com/beliveau-lab/OligoMiner/files/4847634/mouse.txt)

**Comment by brianbeliveau** [comment]
Hi David,

Yes, we have used the LDA mode to design probes for multiple species
without issue.

Looking at your input, I think the issue is that your FASTA header does not
match what the scripts expect: it needs to be chrom:start-stop using the
same scaffold information as the reference genome, e.g. chr1:100000-100035.
This info gets passed to ouputClean via the .fastq header for each probe
candidate, and outputClean will not run properly if it cannot find valid
values for chrom, start, stop. You should see the issue go away if you
either alter your FASTA header or set using the -H flag in blockParse.

Best,

Brian

------------------------------------------------
Brian J. Beliveau, Ph.D.
Assistant Professor of Genome Sciences
University of Washington
He/him/his
+1 978-390-1933 | beliveau.io

**Comment by davidfstein** [comment]
Hi Brian,

Thanks for your help! Does the model actually use the chrom:start-stop information as features for the classification, or only as a way to parse the sam file? I tried it again with ">Tubb3 chr8:123411553-123422015" but I guess I'm still using the wrong header. Looking at the accession on NCBI, https://www.ncbi.nlm.nih.gov/nuccore/NC_000074.6?report=genbank&from=123411553&to=123422015, I thought that my header was correct, sorry if this is outside the scope, but do you know the best way for me to find the correct "chrom:start-stop" metadata when retrieving new sequences?

Best,
David

**Comment by brianbeliveau** [comment]
Hi David,

The chrom:start-stop is used in the parsing of the sam file, which is
important in deciding which candidate probes get passed to the LDA model vs
put directly in the output. This is likely what caused the issue you saw.
The header you would want is ">chr8:123411553-123422015". I would generally
recommend pulling sequence info from UCSC if not from an existing
annotation file.

Hope that helps,

Brian

------------------------------------------------
Brian J. Beliveau, Ph.D.
Assistant Professor of Genome Sciences
University of Washington
He/him/his
+1 978-390-1933 | beliveau.io

**Comment by davidfstein** [comment]
Ok, I'm able to get it working, thanks!
